server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/josematosvicente/bootcamp-cloud-config.git
          default-label: main
          search-paths: config-data
          username: josematosvicente
          password: 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
